version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
  fixme:
    enabled: true
  rubocop:
    enabled: true
exclude_patterns:
  - "spec/"
  - "lib/rggen/core/core_extensions/forwardable_workaround.rb"
