AllCops:
  Exclude:
    - spec/**/*

Style/EndOfLine:
  EnforcedStyle: lf

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/OptionalArguments:
  Exclude:
    - lib/rggen/core/input_base/input_data.rb
