sudo:
  false

email:
  false

cache:
  ../bundler

language:
  ruby
rvm:
  - 2.2
  - 2.2.5
  - 2.2.6
  - 2.3.0
  - 2.3.1
  - 2.4.0
  - 2.4.1

before_install:
  gem install bundler -v 1.14.6

script:
  - bundle exec rake spec
