sudo:
  false

email:
  false

cache:
  ../bundler

language:
  ruby
rvm:
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.8
  - 2.4.5
  - 2.5.3

before_install:
  gem install bundler -v 1.14.6

script:
  - bundle exec rake spec

after_success:
  - bundle exec codeclimate-test-reporter

addons:
  code_climate:
    repo_token:
      2f942f4a05296524cd98df81dff1ee549ddbbf39b1f0bd44e62212452affe5a1
