name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.7', '2.6', '2.5', '2.4']
        frozen_string_literal: ['yes', 'no']
        exclude:
          - ruby: '2.5'
            frozen_string_literal: 'yes'
          - ruby: '2.4'
            frozen_string_literal: 'yes'

    env:
      RUBYOPT: ${{ (matrix.frozen_string_literal == 'yes' && '--enable-frozen-string-literal') || '' }}
      USE_FIXED_GEMS: ${{ matrix.frozen_string_literal }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ matrix.ruby }}-frozen_string_literal-${{ matrix.frozen_string_literal }}-${{ github.sha }}
          restore-keys: |
            gems-${{ runner.os }}-${{ matrix.ruby }}-frozen_string_literal-${{ matrix.frozen_string_literal }}-

      - name: Install gems
        run: |
          gem install -N bundler
          bundle config path vendor/bundle
          bundle install

      - name: Run RSpec
        run: |
          bundle exec rake coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

